<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>PhoenixCodeNav.Portal</AssemblyName>
    <RootNamespace>CodeNav.Portal</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('Windows'))">win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CodeNav.Tests" />
    <InternalsVisibleTo Include="CodeNav.IndexTests" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot/**"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
