using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CodeNav.Core.Indexing;
using CodeNav.Core.Semantic;
using ModelContextProtocol.Server;

namespace CodeNav.Mcp;

/// <summary>
/// Owns: the MCP tool surface — argument handling, result shaping, budgets, and
/// confidence/freshness metadata. Results carry the confidence they earn: "exact" for
/// compiler-backed semantic answers, "indexed" for index/syntax-backed facts, and
/// "heuristic" for naming/text inferences (implementations fallback, related_tests).
/// Does not own: index building/queries (CodeNav.Core).
/// </summary>
[McpServerToolType]
public sealed partial class NavigationTools
{
    internal const int CapabilityDynamicTextBytes = 1024;
    internal const int CapabilityIdentityTextBytes = 96;
    internal const int ExplicitPathInputLimit = 256;
    internal const int PathListInputByteLimit = 64 * 1024;
    internal const int DefaultResultLimit = 20;
    internal const int DefinitionDeadlineMaxMs = 60_000;
    internal const int SemanticNavigationDeadlineMaxMs = 120_000;

    private readonly IndexManager _manager;
    private readonly SemanticService _semantic;
    private readonly IOperationsPortalLauncher _operationsPortalLauncher;
    private readonly string _defaultQueryScope;

    internal string? TestOnlySemanticFailureReason { get; set; }
    internal bool TestOnlyDocumentationIdSeedTimeout { get; set; }
    internal Func<DocumentationIdResolutionResult, DocumentationIdResolutionResult>?
        TestOnlyDocumentationIdResolutionTransform
    { get; set; }
    internal Func<SemanticImplementations, SemanticImplementations>?
        TestOnlyImplementationsResultTransform
    { get; set; }
    internal Func<ProjectSelectorResolution, ProjectSelectorResolution>?
        TestOnlyProjectSelectorResolutionTransform
    { get; set; }
    internal Func<long, long>? TestOnlyReviewBaseBlobElapsedMilliseconds { get; set; }
    internal int? TestOnlySearchSymbolResponseMaxBytes { get; set; }
    internal int? TestOnlyReferencesResponseMaxBytes { get; set; }
    internal int? TestOnlyProjectSelectorResponseMaxBytes { get; set; }
    internal IndexHealth? TestOnlyContextPackHealth { get; set; }

    public NavigationTools(IndexManager manager, SemanticService semantic)
        : this(manager, semantic, new OperationsPortalLauncher())
    {
    }

    internal NavigationTools(IndexManager manager, SemanticService semantic,
        string defaultQueryScope)
        : this(manager, semantic, new OperationsPortalLauncher(), defaultQueryScope)
    {
    }

    internal NavigationTools(
        IndexManager manager,
        SemanticService semantic,
        IOperationsPortalLauncher operationsPortalLauncher,
        string? defaultQueryScope = null)
    {
        _manager = manager;
        _semantic = semantic;
        _operationsPortalLauncher = operationsPortalLauncher;
        _defaultQueryScope = NormalizeDefaultQueryScope(defaultQueryScope ??
            Environment.GetEnvironmentVariable("CODENAV_DEFAULT_QUERY_SCOPE"));
    }

    private static readonly IReadOnlyList<string> TypeKinds =
        IndexedSymbolKinds.TypeDeclarations;

    private string IndexWriterRequired() => Json.Serialize(new
    {
        error = "index_writer_required",
        detail = "This explicit Phoenix instance does not own the writer lease; use an ordinary shared-daemon session.",
        meta = Meta.From(_manager.Health(), "indexed", "text"),
    });

    private string IndexMutationUnavailable() => NotReady() ?? Json.Serialize(new
    {
        error = "index_unavailable",
        detail = "The index writer is not available to accept this operation.",
        meta = Meta.From(_manager.Health(), "indexed", "text"),
    });

    // ---------------------------------------------------------------- helpers

    /// <summary>
    /// Turns a name- or position-target into a concrete (path, line, column) for the
    /// semantic layer, using the index to locate the best declaration for name targets.
    /// </summary>
    private ((string Path, int Line, int? Column)? Target, string? NameHint) ResolveSemanticTarget(
        string? name, string? container, IReadOnlyList<string>? kinds, string? path, int line,
        int column,
        int? arity = null)
    {
        if (path is not null && line > 0)
        {
            return ((NormalizePath(path), line, column > 0 ? column : null), name);
        }
        if (name is null) return (null, null);

        using var q = _manager.OpenQueries();
        // includeGenerated: TRUE (review 4a): the LIVE twin of a dead declaration is typically the
        // WSDL/codegen copy, which carries an <auto-generated> banner — excluding generated files
        // here made the live twin invisible and the orphan gate below useless for the exact
        // production case. The ORDER BY still ranks non-generated first, so picks only change when
        // the non-generated candidates are dead.
        var hits = q.SearchSymbols(
            name, "exact", kinds, 20, includeGenerated: true, arity: arity,
            language: "cs");
        if (container is { } c)
        {
            hits = hits.Where(h =>
                (h.Container?.Contains(c, StringComparison.OrdinalIgnoreCase) ?? false) ||
                (h.Ns?.Contains(c, StringComparison.OrdinalIgnoreCase) ?? false)).ToList();
        }
        // NEVER target an uncompiled declaration (3tz, the dead-twin bug): a file no project compiles
        // is in no compilation, so semantic resolution against it can only fail — while a LIVE twin of
        // the same symbol (e.g. the WSDL-generated one) exists elsewhere. The old pick even preferred
        // the dead twin: non-generated files sort first. Fall back to orphaned-only when there is no
        // live declaration at all (then semantic fails honestly and the heuristic path takes over).
        if (hits.Count > 0)
        {
            var orphaned = q.OrphanedPaths(hits.Select(h => h.FilePath).Distinct(StringComparer.OrdinalIgnoreCase).ToList());
            if (orphaned.Count > 0)
            {
                var live = hits.Where(h => !orphaned.Contains(h.FilePath)).ToList();
                if (live.Count > 0) hits = live;
            }
        }
        var best = hits
            .OrderBy(h => h.Kind switch { "interface" => 0, "class" => 1, "struct" => 1, "enum" => 1, _ => 2 })
            .FirstOrDefault();
        if (best is null) return (null, name);
        return ((best.FilePath, best.StartLine, null), name);
    }

    // Cap on declaration sites emitted for one symbol. A namespace or heavily-partial type can
    // have hundreds of spans; this bounds the count for tools that serialize it via a plain
    // Serialize (implementations/references/etc.). definition additionally routes its (single)
    // declaration list through WithListBudget for a hard byte bound; this cap keeps the common
    // case small and gives an early declarationsTruncated signal.
    private const int MaxDeclarationSites = 20;

    // Kept single-arg so method-group use (.Select(SemanticSymbolJson)) still binds.
    private static object SemanticSymbolJson(SemanticDeclaration d) => SemanticSymbolCore(d, includeDeclarations: true);

    // Identity without the declaration list — for definition, which renders declarations once
    // in its own budgeted top-level array (avoids serializing the same sites twice).
    private static object SemanticIdentityJson(SemanticDeclaration d) => SemanticSymbolCore(d, includeDeclarations: false);

    private static object SemanticSymbolCore(SemanticDeclaration d, bool includeDeclarations)
    {
        var sites = includeDeclarations ? d.Declarations.Take(MaxDeclarationSites + 1).ToList() : null;
        int returnedDeclarations = Math.Min(d.Declarations.Count, MaxDeclarationSites);
        bool declarationSitesTruncated = includeDeclarations &&
                                         d.Declarations.Count > MaxDeclarationSites;
        return new
        {
            display = d.SymbolDisplay,
            documentationCommentId = d.DocumentationCommentId,
            d.Kind,
            containingType = d.ContainingType,
            ns = d.Namespace,
            assembly = d.Assembly,
            declarations = sites?.Take(MaxDeclarationSites).Select(s => new { s.Path, s.StartLine, s.EndLine, project = s.Project }),
            declarationsTotal = includeDeclarations ? d.Declarations.Count : (int?)null,
            declarationsReturned = includeDeclarations ? returnedDeclarations : (int?)null,
            declarationsTruncated = declarationSitesTruncated
                ? $"more than {MaxDeclarationSites} declaration sites — narrow the query or use references"
                : (string?)null,
            declarationsNoteId = declarationSitesTruncated
                ? NoteIds.SemanticDeclarationSitesBudget
                : null,
        };
    }

    private const int CoverageIdentityJsonBytes = 256;

    private static string CoverageIdentity(string value) =>
        Json.JsonStringPrefix(value, CoverageIdentityJsonBytes, out _);

    private static bool CoverageIdentityTruncated(string value)
    {
        _ = Json.JsonStringPrefix(value, CoverageIdentityJsonBytes, out bool truncated);
        return truncated;
    }

    private static object CoverageJson(ClusterCoverage c)
    {
        var causeGroups = (c.FailedProjectCauses ??
                new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase))
            .Where(pair => c.FailedProjects.Contains(pair.Key,
                StringComparer.OrdinalIgnoreCase))
            .GroupBy(pair => pair.Value, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal)
            .ToList();
        var causeSample = causeGroups.Take(8).Select(group =>
        {
            List<string> projects = group.Select(pair => pair.Key)
                .OrderBy(value => value, StringComparer.OrdinalIgnoreCase).ToList();
            return new
            {
                cause = group.Key,
                projectCount = projects.Count,
                projects = projects.Take(4).Select(CoverageIdentity).ToList(),
                projectsTruncated = projects.Count > 4 ||
                                    projects.Any(CoverageIdentityTruncated)
                    ? true
                    : (bool?)null,
            };
        }).ToList();
        return new
        {
            loadedProjects = c.LoadedProjects,
            requestedProjects = c.RequestedProjects,
            // Field 0.7.0: SymbolFinder scans the WHOLE solution (including projects loaded by earlier
            // calls), so hits can legitimately exceed the requested set — this makes that legible
            // instead of "coverage 1/1 but 8 hits from 8 projects".
            solutionProjects = c.SolutionProjects > 0 ? c.SolutionProjects : (int?)null,
            skippedProjects = c.SkippedProjects.Count > 0
                ? c.SkippedProjects.Take(8).Select(CoverageIdentity).ToList()
                : null,
            skippedProjectCount = c.SkippedProjects.Count > 0 ? c.SkippedProjects.Count : (int?)null,
            skippedProjectsTruncated = c.SkippedProjects.Count > 8 ||
                                       c.SkippedProjects.Any(CoverageIdentityTruncated)
                ? true
                : (bool?)null,
            failedProjects = c.FailedProjects.Count > 0
                ? c.FailedProjects.Take(8).Select(CoverageIdentity).ToList()
                : null,
            failedProjectCount = c.FailedProjects.Count > 0 ? c.FailedProjects.Count : (int?)null,
            failedProjectsTruncated = c.FailedProjects.Count > 8 ||
                                      c.FailedProjects.Any(CoverageIdentityTruncated)
                ? true
                : (bool?)null,
            failedProjectCauses = causeSample.Count > 0 ? causeSample : null,
            failedProjectCauseCount = causeGroups.Count > 0 ? causeGroups.Count : (int?)null,
            failedProjectCausesTruncated = causeGroups.Count > 8 ? true : (bool?)null,
            unprovenFriendAssemblyProjects = c.UnprovenFriendAssemblyProjects is { Count: > 0 } unproven
                ? unproven.Take(8).Select(CoverageIdentity).ToList()
                : null,
            unprovenFriendAssemblyProjectCount = c.UnprovenFriendAssemblyProjects is { Count: > 0 }
                ? c.UnprovenFriendAssemblyProjects.Count
                : (int?)null,
            unprovenFriendAssemblyProjectsTruncated = c.UnprovenFriendAssemblyProjects is { Count: > 0 } identities &&
                                                       (identities.Count > 8 ||
                                                        identities.Any(CoverageIdentityTruncated))
                ? true
                : (bool?)null,
            frameworkRefsAvailable = c.FrameworkRefsAvailable,
            resolvedPackageDllCount = c.ResolvedPackageDllCount,
            frameworkRefsSource = c.FrameworkRefsSource,
        };
    }

    private static bool IsFSharpScriptPath(string path) =>
        Path.GetExtension(path).Equals(".fsx", StringComparison.OrdinalIgnoreCase);

    private string UnsupportedLanguage(string path, string language, string operation)
    {
        bool compileOwnedFSharp = false;
        string extension = Path.GetExtension(path);
        if (language == "fs" &&
            (extension.Equals(".fs", StringComparison.OrdinalIgnoreCase) ||
             extension.Equals(".fsi", StringComparison.OrdinalIgnoreCase)))
        {
            using var queries = _manager.OpenQueries();
            compileOwnedFSharp = queries.ProjectsContaining(path)
                .Any(project => project.Language == "fs");
        }
        return UnsupportedLanguageForTest(_manager.Health(), path, language, operation,
            compileOwnedFSharp);
    }

    internal static string UnsupportedLanguageForTest(IndexHealth health, string path,
        string language, string operation, bool compileOwnedFSharp = false)
    {
        string extension = Path.GetExtension(path);
        if (language == "fs" && extension.Equals(".fsx", StringComparison.OrdinalIgnoreCase))
            language = "fsx";
        bool fsharpSemanticEligible = language == "fs" && compileOwnedFSharp &&
            (extension.Equals(".fs", StringComparison.OrdinalIgnoreCase) ||
             extension.Equals(".fsi", StringComparison.OrdinalIgnoreCase));
        bool fsharpSyntaxIndexed = language == "fs" &&
            (extension.Equals(".fs", StringComparison.OrdinalIgnoreCase) ||
             extension.Equals(".fsi", StringComparison.OrdinalIgnoreCase));
        return Json.WithStringBudget(path, 4096, (boundedPath, pathTruncated) => new
        {
            error = "unsupported_language",
            operation,
            path = boundedPath,
            pathTruncated = pathTruncated ? true : (bool?)null,
            language,
            supportedLanguages = operation is "symbol_at" or "definition" or "references" or "implementations" or "callers" or "callees" or "outline" or "search_symbol"
                ? new[] { "cs", "fs" }
                : new[] { "cs" },
            availableForFile = fsharpSemanticEligible
                ? new[] { "find_file", "search_text", "source_context", "projects_containing", "search_symbol", "outline", "symbol_at", "definition", "references", "implementations", "callers", "callees" }
                : fsharpSyntaxIndexed
                ? new[] { "find_file", "search_text", "source_context", "projects_containing", "search_symbol" }
                : new[] { "find_file", "search_text", "source_context", "projects_containing" },
            detail = fsharpSemanticEligible
                ? "F# supports text, project-graph navigation, FCS outlines, position-based symbol_at, definition through its F# ProjectReference closure under the evaluated MSBuild transitivity policy, compiler-bound references, implementations, and callers across proven F# workspace dependents, and body-local callees through the source ProjectReference closure for compile-owned .fs/.fsi files. Exact child TFMs win; table-compatible single-target netstandard2.0/2.1 children resolve, while compatibility fallback from multi-target children and netstandard1.x compile inputs fail closed. F# hierarchy and semantic navigation through C# ProjectReference targets remain unavailable."
                : language == "fsx"
                    ? "F# script files are text-only; indexed F# declaration search covers .fs and .fsi project inputs."
                    : language == "fs"
                    ? "This F# file is not a compile-owned .fs/.fsi semantic input; syntax-indexed search_symbol plus text and project-graph navigation remain available."
                    : $"The indexed language '{language}' supports text navigation only; C# syntax and compiler semantics are not available.",
            meta = Meta.From(health, "indexed", "text"),
        });
    }

    private string? UnsupportedLanguageAtPath(string? path, string operation)
    {
        if (string.IsNullOrWhiteSpace(path)) return null;
        string normalized = NormalizePath(path);
        using var q = _manager.OpenQueries();
        return q.FileByPath(normalized) is { Language: not "cs" } file
            ? UnsupportedLanguage(normalized, file.Language, operation)
            : null;
    }

    /// <summary>Combines an explicit excludePath glob with the first-party query scope's
    /// whole-segment vendor globs into one exclude list (null when empty, so callers pass null for
    /// "no filter"). The scope uses <see cref="IndexQueries.VendorExcludeGlobs"/> — a complete,
    /// scan-free exclusion that matches exactly what the per-hit noise flag reports.</summary>
    private static IReadOnlyList<string>? BuildExcludes(string? excludePath, bool firstPartyScope)
    {
        var list = new List<string>();
        if (excludePath is { Length: > 0 } ex) list.Add(ex);
        if (firstPartyScope) list.AddRange(IndexQueries.VendorExcludeGlobs());
        return list.Count > 0 ? list.Distinct(StringComparer.OrdinalIgnoreCase).ToList() : null;
    }

    private sealed record QueryScopeSelection(
        string ConfiguredDefault,
        string Applied,
        bool DefaultApplied);

    internal static string NormalizeDefaultQueryScope(string? configured) =>
        configured?.Trim().ToLowerInvariant() switch
        {
            "first_party" => "first_party",
            _ => "all",
        };

    private (QueryScopeSelection? Selection, string? Error) ResolveQueryScope(string? requested)
    {
        string value = requested is null || requested.Length == 0
            ? "default"
            : requested.Trim().ToLowerInvariant();
        if (value is not ("default" or "all" or "first_party"))
        {
            return (null, Json.Serialize(new
            {
                error = "bad_request",
                field = "queryScope",
                value = requested,
                validValues = new[] { "default", "all", "first_party" },
                detail = "queryScope must be 'default', 'all', or 'first_party'.",
                meta = Meta.From(_manager.Health(), "indexed", "text"),
            }));
        }
        bool defaultApplied = value == "default";
        string applied = value switch
        {
            "all" => "all",
            "first_party" => "first_party",
            _ => _defaultQueryScope,
        };
        return (new QueryScopeSelection(
            _defaultQueryScope, applied, defaultApplied), null);
    }

    /// <summary>Resolves a symbolId handle to its indexed declaration row. Accepts the idx:NNN
    /// handle (from any search_symbol / symbol_at / definition result) — index-local, so it changes
    /// on reindex. Compiler-stable ids use the separate documentationCommentId argument. Returns the
    /// hit on success, or an error-JSON string to hand straight back to the caller.</summary>
    private (SymbolHit? Hit, string? Error) ResolveSymbolIdHandle(string symbolId)
    {
        // Handle shape: idx:<rowid>[~<fingerprint>]. The fingerprint is optional so a hand-typed
        // idx:<rowid> still resolves (best-effort, unverified); emitted handles always carry it.
        string body = symbolId.StartsWith("idx:", StringComparison.Ordinal) ? symbolId[4..] : "";
        string? fp = null;
        int tilde = body.IndexOf('~');
        if (tilde >= 0) { fp = body[(tilde + 1)..]; body = body[..tilde]; }
        if (body.Length == 0 || !long.TryParse(body, out long id))
        {
            return (null, Json.Serialize(new
            {
                error = "bad_request",
                detail = "symbolId must be an 'idx:NNN' handle (from a prior search_symbol / symbol_at / definition result). Pass a Roslyn id such as 'T:Ns.Type' through documentationCommentId instead.",
            }));
        }
        using var q = _manager.OpenQueries();
        var hit = q.SymbolById(id);
        if (hit is null)
        {
            return (null, Json.Serialize(new
            {
                error = "symbol_not_found",
                detail = $"No indexed symbol with id {id}. 'idx:' handles are index-local — re-run search_symbol for a current handle.",
            }));
        }
        if (fp is not null && !FingerprintMatches(hit, fp))
        {
            // The rowid still exists but now holds a DIFFERENT symbol (a reindex reused it). Refuse
            // rather than return the wrong symbol as if the handle were exact.
            return (null, Json.Serialize(new
            {
                error = "stale_handle",
                detail = $"symbolId 'idx:{id}' now refers to a different symbol ({hit.Name}) — the index changed since the handle was issued. Re-run search_symbol for a current handle.",
            }));
        }
        return (hit, null);
    }

    private static string? OperatorDeclarationKey(SymbolHit hit) =>
        hit.Kind == "operator" && !string.IsNullOrEmpty(hit.DeclarationKey)
            ? hit.DeclarationKey
            : null;

    private string OperatorReferencesRequireSemantic(string reason, object? timing) =>
        Json.Serialize(new
        {
            error = "semantic_required",
            operation = "references",
            kind = "operator",
            partialReason = reason,
            timing,
            detail = "Operator idx handles require compiler-semantic references so the canonical declaration key remains pinned; indexed text candidates cannot distinguish overload identity.",
            hint = "Retry without pathGlob/excludePath using mode='semantic' or mode='auto'.",
            meta = Meta.From(_manager.Health(), "indexed", "semantic"),
        });

    private string OperatorReferencesBadRequest(
        string field, string reason, string expected, string detail) => Json.Serialize(new
        {
            error = "bad_request",
            field,
            reason,
            expected,
            operation = "references",
            kind = "operator",
            detail,
            meta = Meta.From(_manager.Health(), "indexed", "semantic"),
        });

    /// <summary>Expands the cluster_cold_load token at the point of confusion: the deadline
    /// canceled compilation loading, so the one advised retry should use more of the family's
    /// documented timeout budget when available. Every other reason passes through untouched,
    /// and the token stays the string's prefix so it remains machine-matchable.</summary>
    internal static string? ExpandReason(string? reason) => // internal: token contract pinned by tests
        reason == "cluster_cold_load"
            ? "cluster_cold_load — the request deadline canceled compilation loading; retry once, increasing timeoutMs when the prior request was below the tool's documented maximum"
            : reason;

    /// <summary>Transient semantic failures keep their established partialReason token while
    /// carrying a separate machine-readable retry signal. A retry is advice, not an automatic
    /// second invocation or a hidden deadline increase.</summary>
    internal static bool SemanticRetryRecommended(string? reason) =>
        reason is not null &&
        (reason.StartsWith("cluster_cold_load", StringComparison.Ordinal) ||
         reason.StartsWith("semantic_timeout", StringComparison.Ordinal) ||
         reason.StartsWith("index_snapshot_changed", StringComparison.Ordinal));

    internal static string? SemanticRetryHint(string? reason, string operation,
        int deadlineMs, int maxDeadlineMs)
    {
        if (!SemanticRetryRecommended(reason)) return null;
        if (reason!.StartsWith("index_snapshot_changed", StringComparison.Ordinal))
            return $"Retry {operation} once with the same arguments; an index refresh landed during the request.";
        if (reason.StartsWith("cluster_cold_load", StringComparison.Ordinal))
        {
            return deadlineMs < maxDeadlineMs
                ? $"Retry {operation} once with a larger timeoutMs (this request used {deadlineMs} ms; the maximum is {maxDeadlineMs} ms); the request deadline canceled the semantic cluster load."
                : $"Retry {operation} once with the same arguments; the load canceled at the maximum timeoutMs may complete because prepared inputs are reused.";
        }
        return $"Retry {operation} once with the same arguments; if it remains partial, narrow the target or explicitly choose a larger timeoutMs.";
    }

    /// <summary>Wire vocabulary for edge provenance (bxw): the stored kind ('project'/'assembly')
    /// maps to 'projectReference'/'hintPathReference' — 'projectReference' predates provenance on
    /// the wire (project_graph hardcoded it), so the common case keeps its established value.
    /// Same tokens everywhere kind/via appears (project_graph, dependency_path, context_pack).</summary>
    private static string EdgeKind(string storedKind) =>
        storedKind == "assembly" ? "hintPathReference" : "projectReference";

    /// <summary>Structured attribution for reference groups whose files sit in NO project's
    /// compile set (bxw): the payload used to ship the magic display string "(no project)",
    /// which callers had to know to string-match. Now the project field is null — which the
    /// house serialization OMITS (WhenWritingNull) — and orphaned:true rides alongside as the
    /// positive discriminator, the same 'orphaned' vocabulary search_symbol/repo_overview use.
    /// Nullable bool so compiled rows stay clean (orphaned omitted too).</summary>
    private static string? GroupProject(string project) =>
        project == IndexQueries.NoProjectGroup ? null : project;

    private static bool? GroupOrphaned(string project) =>
        project == IndexQueries.NoProjectGroup ? true : null;

    /// <summary>Stable, cross-process identity hash of a symbol row. v3 binds the declaration to
    /// the file's existing content hash and deterministic syntax ordinal among declarations that
    /// share a source line, so declarations with identical local display identity remain distinct
    /// while any file edit invalidates its handles conservatively. The ordinal is projected in the
    /// same read query as the symbol; this adds no column, binding, crypto, or allocation to every
    /// symbol during indexing and keeps response shaping free of follow-up queries.</summary>
    private static string Fingerprint(SymbolHit s)
    {
        string localIdentity = string.Join('\u001e', s.Ns ?? "", s.Container ?? "",
            !string.IsNullOrEmpty(s.DeclarationKey) ? s.DeclarationKey : s.Signature);
        string identity = string.Join('\u001f', s.Name, s.Kind,
            s.Arity.ToString(System.Globalization.CultureInfo.InvariantCulture),
            s.StartLine.ToString(System.Globalization.CultureInfo.InvariantCulture),
            s.FilePath, s.FileHash.ToString(System.Globalization.CultureInfo.InvariantCulture),
            s.OrdinalOnLine.ToString(System.Globalization.CultureInfo.InvariantCulture),
            localIdentity);
        return "v3-" + Convert.ToHexString(
            SHA256.HashData(Encoding.UTF8.GetBytes(identity))).ToLowerInvariant();
    }

    private static bool FingerprintMatches(SymbolHit s, string fingerprint)
    {
        if (fingerprint.StartsWith("v3-", StringComparison.Ordinal))
            return string.Equals(fingerprint, Fingerprint(s), StringComparison.Ordinal);

        // Older fingerprints cannot prove the current file epoch. Fail closed instead of silently
        // accepting a row id that may have been reassigned by a rebuild or delta refresh.
        return false;
    }

    private static object SymbolJson(SymbolHit s) => new
    {
        // idx:<rowid>~<identity fingerprint>. The fingerprint lets a rowid that delta refresh
        // reused/reassigned be DETECTED on the way back in (stale_handle) rather than silently
        // resolving to a different symbol — the id alone is not stable across reindex.
        symbolId = $"idx:{s.Id}~{Fingerprint(s)}",
        s.Name,
        s.Kind,
        s.Arity,
        ns = s.Ns,
        containingType = s.Container,
        s.Signature,
        s.Accessibility,
        // Inheritance/lifetime modifiers (bt7): "virtual"/"override"/"abstract"/"static sealed"...
        // Omitted when none — in deep hierarchies this picks the override site without opening files.
        modifiers = s.Modifiers,
        // Per-accessor accessibility (hu7): { get: "public", set: "private" } — ONLY when an
        // accessor differs from the member's own accessibility (silent-when-nothing-to-say).
        accessors = AccessorsJson(s.Accessors),
        path = s.FilePath,
        s.StartLine,
        s.EndLine,
        isPartial = s.IsPartial ? true : (bool?)null,
        isGenerated = s.FileIsGenerated ? true : (bool?)null,
        // Best-effort "this hit lives under a vendored/generated dir" signal (only present when
        // true). Lets a caller spot third-party noise without first-party scope, or excludePath it.
        noise = IndexQueries.IsVendorPath(s.FilePath) ? true : (bool?)null,
        // "No project compiles this file" (only present when true) — the compile-graph signal grep
        // lacks. 3tz: Include globs expanded, Remove honored; residual gaps are shared .projitems,
        // props-level globs, and ignored Conditions — near-proof, not absolute proof.
        orphaned = s.IsOrphaned ? true : (bool?)null,
        attributes = s.AttrMarkers,
    };

    /// <summary>Parses the stored "get=public;set=private" accessor split into a structured
    /// object (hu7). Null (omitted) when the member's accessors are uniform.</summary>
    private static Dictionary<string, string>? AccessorsJson(string? accessors)
    {
        if (accessors is null) return null;
        var map = new Dictionary<string, string>();
        foreach (var part in accessors.Split(';', StringSplitOptions.RemoveEmptyEntries))
        {
            int eq = part.IndexOf('=');
            if (eq > 0) map[part[..eq]] = part[(eq + 1)..];
        }
        return map.Count > 0 ? map : null;
    }

    private string? NotReady()
    {
        if (_manager.IsQueryable) return null;
        var h = _manager.Health();
        bool retryRecommended = IndexRetryRecommended(h);
        return Json.Serialize(new
        {
            error = h.State == "building" ? "index_building" : "index_unavailable",
            state = h.State,
            detail = h.Error,
            // The progress struct rides IN the error (field: "otherwise callers still have to
            // poll server_capabilities separately") — phase + monotonic counters + elapsed,
            // filesTotal omitted until the scan knows it, no fabricated ETA/percent (bead two).
            progress = ProgressJson(h),
            hint = h.State == "building"
                ? "The workspace index is still building (first run). Inspect server_capabilities index.progress, wait while it advances, and retry after index.state is ready."
                : "The workspace index is unavailable. Inspect server_capabilities for the cause and recovery before retrying.",
            retryRecommended,
            retryHint = retryRecommended
                ? IndexProgressRetryHint
                : IndexTerminalRetryHint,
        });
    }

    private const string IndexProgressRetryHint =
        "Inspect server_capabilities.index.progress. If server_capabilities.index.state is not ready, wait until it becomes ready; then retry the original call once.";

    private const string IndexTerminalRetryHint =
        "Inspect server_capabilities.index.error and the reported recovery; retrying does not help until the cause is resolved.";

    /// <summary>The complete IndexManager state vocabulary is mapped explicitly in the context of
    /// an already non-queryable gate. A follower's failed publication is the writer's transient
    /// rebuild window; a writer/unavailable failed publication remains terminal. Unknown state or
    /// access-mode values fail closed instead of silently becoming retryable.</summary>
    internal static bool IndexRetryRecommended(IndexHealth health)
    {
        if (health.AccessMode is not (IndexManager.WriterAccessMode or
            IndexManager.FollowerAccessMode or IndexManager.UnavailableAccessMode))
            return false;

        return health.State switch
        {
            "missing" => true,
            "building" => true,
            "refreshing" => true,
            "stale" => true,
            // This helper is called only after IsQueryable returned false. A nominally ready
            // manager at that gate is crossing a publication or destination-authority boundary.
            "ready" => true,
            "failed" => health.AccessMode == IndexManager.FollowerAccessMode,
            _ => false,
        };
    }

    /// <summary>Test seam: the shared progress emitter — the silent-when-zero (efa) and
    /// gated-estimate (0tn) emission rules are pinned by tests through this.</summary>
    internal static object? ProgressJsonForTest(IndexHealth h) => ProgressJson(h);

    /// <summary>Build-progress envelope shared by server_capabilities.index and the
    /// index_building error body — one shape everywhere; null (omitted) unless building.</summary>
    private static object? ProgressJson(IndexHealth h)
    {
        if (h.Progress is not { } p) return null;
        string phase = Json.Utf8Prefix(p.Phase, CapabilityDynamicTextBytes,
            out bool phaseTruncated);
        return new
        {
            phase,
            phaseTruncated = phaseTruncated ? true : (bool?)null,
            phaseBytes = phaseTruncated ? Json.Utf8Bytes(p.Phase) : (int?)null,
            filesIndexed = p.FilesIndexed,
            filesTotal = p.FilesTotal,
            elapsedMs = p.ElapsedMs,
            // efa: silent on a clean build — the counters exist to make a LOSSY build visible
            // (skipped reads are absent from the index until a delta refresh retries them;
            // failed csproj parses mean guessed compile sets), not to add noise to a good one.
            filesSkipped = p.FilesSkipped > 0 ? p.FilesSkipped : (int?)null,
            projectsFailed = p.ProjectsFailed > 0 ? p.ProjectsFailed : (int?)null,
            // 0tn: DERIVED from the monotonic counters over the indexing_files phase's own
            // clock, present only once measurable (>=100 files over >=1s) — labeled estimates
            // that may fluctuate; still no percent field (derive % from the counters).
            filesPerSecond = p.FilesPerSecond,
            estimatedRemainingMs = p.EstimatedRemainingMs,
        };
    }

    // Cursor is "o:<offset>" or, for a mode-carrying tool (search_symbol auto), "o:<offset>:<mode>".
    private static (int Limit, int Offset, string? Mode) Page(int limit, string? cursor)
    {
        limit = Math.Clamp(limit, 1, 100);
        int offset = 0;
        string? mode = null;
        if (cursor is not null && cursor.StartsWith("o:", StringComparison.Ordinal))
        {
            string rest = cursor[2..];
            int colon = rest.IndexOf(':');
            string offsetPart = colon < 0 ? rest : rest[..colon];
            if (int.TryParse(offsetPart, out int parsed) && parsed > 0) offset = parsed;
            if (colon >= 0 && colon + 1 < rest.Length) mode = rest[(colon + 1)..];
        }
        return (limit, offset, mode);
    }

    internal static bool TryParseStringList(
        string? value,
        string field,
        out List<string>? items,
        out string? detail)
    {
        items = null;
        detail = null;
        if (value is null || value.Length == 0) return true;
        if (string.IsNullOrWhiteSpace(value))
        {
            detail = $"{field} must not be whitespace-only.";
            return false;
        }
        string trimmed = value.Trim();
        if (trimmed[0] == '[')
        {
            try
            {
                using JsonDocument document = JsonDocument.Parse(trimmed);
                if (document.RootElement.ValueKind != JsonValueKind.Array)
                {
                    detail = $"{field} must be comma-separated text or a JSON array of strings.";
                    return false;
                }
                items = new List<string>();
                foreach (JsonElement item in document.RootElement.EnumerateArray())
                {
                    if (item.ValueKind != JsonValueKind.String ||
                        string.IsNullOrWhiteSpace(item.GetString()))
                    {
                        detail = $"Every JSON-array {field} item must be a non-empty string.";
                        return false;
                    }
                    items.Add(item.GetString()!.Trim());
                }
                if (items.Count == 0)
                {
                    detail = $"The JSON-array {field} value must contain at least one item.";
                    return false;
                }
                return true;
            }
            catch (JsonException)
            {
                detail = $"{field} starts like a JSON array but is not a valid JSON array of strings.";
                return false;
            }
        }
        if (trimmed[0] is '"' or '{')
        {
            detail = $"{field} must be comma-separated text or a JSON array of strings.";
            return false;
        }
        string[] csvItems = value.Split(',', StringSplitOptions.TrimEntries);
        if (csvItems.Length == 0 || csvItems.Any(string.IsNullOrWhiteSpace))
        {
            detail = $"Every comma-separated {field} item must be non-empty.";
            return false;
        }
        items = csvItems.ToList();
        return true;
    }

    private string StringListBadRequest(string field, string? detail) => Json.Serialize(new
    {
        error = "bad_request",
        field,
        detail,
        meta = Meta.From(_manager.Health(), "indexed", "syntax"),
    });

    private string? NormalizeDocumentationCommentId(ref string? documentationCommentId)
    {
        if (documentationCommentId is null or "") return null;
        if (string.IsNullOrWhiteSpace(documentationCommentId))
        {
            return Json.Serialize(new
            {
                error = "bad_request",
                field = "documentationCommentId",
                detail = "documentationCommentId must not be whitespace-only. Use an empty string to omit it.",
                meta = Meta.From(_manager.Health(), "indexed", "syntax"),
            });
        }
        documentationCommentId = documentationCommentId.Trim();
        return null;
    }

    private sealed record DocumentationTarget(
        string Name,
        string Path,
        int Line,
        int Column,
        string CanonicalDocumentationCommentId,
        DocumentationIdResolutionCoverage Coverage,
        IndexSnapshotIdentity SnapshotIdentity,
        long ResolutionElapsedMs);

    private (DocumentationTarget? Target, string? Error) ResolveDocumentationTarget(
        string documentationCommentId,
        string operation,
        int deadlineMs,
        bool implementationsOnly,
        int maxDeadlineMs,
        CancellationToken cancellationToken,
        System.Diagnostics.Stopwatch deadlineStopwatch,
        SemanticColdStartTimingBox coldStartTiming)
    {
        string id = documentationCommentId.Trim();
        if (id.Length < 3 || id[1] != ':' || id[2..].Length == 0 ||
            id.Any(char.IsWhiteSpace) || id.Any(char.IsControl))
        {
            return (null, DocumentationIdError(documentationCommentId, (boundedId, truncated) => new
            {
                error = "bad_request",
                field = "documentationCommentId",
                documentationCommentId = boundedId,
                documentationCommentIdTruncated = truncated ? true : (bool?)null,
                documentationCommentIdBytes = truncated
                    ? Json.Utf8Bytes(documentationCommentId)
                    : (int?)null,
                detail = "Expected a Roslyn declaration id such as T:Ns.Type or M:Ns.Type.Method(System.String).",
                supportedPrefixes = new[] { "T:", "M:", "P:", "F:", "E:" },
                meta = Meta.From(_manager.Health(), "indexed", "syntax"),
            }));
        }
        char prefix = id[0];
        if (prefix is not ('T' or 'M' or 'P' or 'F' or 'E'))
        {
            return (null, DocumentationIdError(id, (boundedId, truncated) => new
            {
                error = "unsupported_documentation_id_kind",
                operation,
                documentationCommentId = boundedId,
                documentationCommentIdTruncated = truncated ? true : (bool?)null,
                documentationCommentIdBytes = truncated ? Json.Utf8Bytes(id) : (int?)null,
                prefix = id[..2],
                supportedPrefixes = new[] { "T:", "M:", "P:", "F:", "E:" },
                detail = "Only declaration ids are supported; namespace and error ids are not retargeted.",
                meta = Meta.From(_manager.Health(), "indexed", "syntax"),
            }));
        }
        string signature = id[2..];
        int parameterStart = signature.IndexOf('(');
        if (parameterStart >= 0) signature = signature[..parameterStart];
        bool unsupportedImplementationKind = prefix == 'F' ||
            prefix == 'M' &&
            (signature.EndsWith(".#ctor", StringComparison.Ordinal) ||
             signature.EndsWith(".#cctor", StringComparison.Ordinal) ||
             signature.Split('.').Last().StartsWith("op_", StringComparison.Ordinal));
        if (implementationsOnly && unsupportedImplementationKind)
        {
            return (null, DocumentationIdError(id, (boundedId, truncated) => new
            {
                error = "unsupported_symbol_kind",
                operation,
                documentationCommentId = boundedId,
                documentationCommentIdTruncated = truncated ? true : (bool?)null,
                documentationCommentIdBytes = truncated ? Json.Utf8Bytes(id) : (int?)null,
                kind = prefix == 'F' ? "field" : "method",
                detail = "Implementations does not model fields, constructors, or operators. The documentation id was not retargeted to its containing type.",
                meta = Meta.From(_manager.Health(), "indexed", "semantic"),
            }));
        }

        string declaring = prefix == 'T'
            ? signature
            : signature.Contains('.')
                ? signature[..signature.LastIndexOf('.')]
                : "";
        string[] declaringSegments = declaring.Split('.', StringSplitOptions.RemoveEmptyEntries)
            .Select(segment =>
            {
                int generic = segment.IndexOfAny(['`', '{']);
                return generic >= 0 ? segment[..generic] : segment;
            })
            .Where(segment => segment.Length > 0)
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (declaringSegments.Length == 0)
        {
            return (null, DocumentationIdError(id, (boundedId, truncated) => new
            {
                error = "bad_request",
                field = "documentationCommentId",
                documentationCommentId = boundedId,
                documentationCommentIdTruncated = truncated ? true : (bool?)null,
                documentationCommentIdBytes = truncated ? Json.Utf8Bytes(id) : (int?)null,
                detail = "The declaration id does not contain a declaring type.",
                meta = Meta.From(_manager.Health(), "indexed", "syntax"),
            }));
        }

        string candidateName = declaringSegments[^1];
        DocumentationIdResolutionResult resolution = _semantic
            .ResolveDocumentationCommentIdAsync(
                candidateName, id, deadlineMs, cancellationToken,
                forceSeedTimeoutForTest: TestOnlyDocumentationIdSeedTimeout,
                coldStartTiming: coldStartTiming)
            .GetAwaiter().GetResult();
        if (TestOnlyDocumentationIdResolutionTransform is not null)
            resolution = TestOnlyDocumentationIdResolutionTransform(resolution);

        string TerminalResponse(string response, string result, string? reason)
        {
            _semantic.EmitTerminalTelemetry(
                operation, result, reason, coldStartTiming.Timing);
            return response;
        }

        if (resolution.FailReason == "documentation_id_seed_timeout")
        {
            return (null, TerminalResponse(Json.WithStringBudget(
                candidateName, Json.HardBudgetBytes,
                (boundedCandidateName, candidateNameTruncated) =>
                    System.Text.Json.Nodes.JsonNode.Parse(DocumentationIdError(id,
                        (boundedId, truncated) => new
                        {
                            error = "semantic_unavailable",
                            operation,
                            documentationCommentId = boundedId,
                            documentationCommentIdTruncated = truncated ? true : (bool?)null,
                            documentationCommentIdBytes = truncated ? Json.Utf8Bytes(id) : (int?)null,
                            partialReason = "documentation_id_seed_timeout",
                            retryRecommended = true,
                            retryHint = deadlineMs < maxDeadlineMs
                                ? $"Retry the same semantic request once; if pre-compiler documentation-id discovery (seed, owner, and dependency closure) times out again, choose a timeoutMs up to {maxDeadlineMs}."
                                : "Retry the same semantic request once; if pre-compiler documentation-id discovery (seed, owner, and dependency closure) times out again at the maximum deadline, inspect index health after the exact declaration probe instead of increasing timeoutMs.",
                            retry = candidateNameTruncated
                                ? null
                                : new
                                {
                                    tool = "search_symbol",
                                    arguments = new
                                    {
                                        query = boundedCandidateName,
                                        match = "exact",
                                        lang = "csharp",
                                    },
                                },
                            timing = new
                            {
                                deadlineMs,
                                effectiveDeadlineMs = deadlineMs,
                                maxDeadlineMs,
                                elapsedMs = deadlineStopwatch.ElapsedMilliseconds,
                                documentationIdResolutionMs = deadlineStopwatch.ElapsedMilliseconds,
                                semanticColdStart = coldStartTiming.Timing,
                            },
                            meta = Meta.From(_manager.Health(), "indexed", "semantic"),
                        }))!), "degraded", "documentation_id_seed_timeout"));
        }
        if (resolution.Matches is null)
        {
            return (null, TerminalResponse(DocumentationIdErrorWithCoverage(
                id, resolution.Coverage,
                (boundedId, truncated, skippedProjects, skippedProjectsTruncated) => new
                {
                    error = "semantic_unavailable",
                    operation,
                    documentationCommentId = boundedId,
                    documentationCommentIdTruncated = truncated ? true : (bool?)null,
                    documentationCommentIdBytes = truncated ? Json.Utf8Bytes(id) : (int?)null,
                    partialReason = ExpandReason(resolution.FailReason),
                    retryRecommended = SemanticRetryRecommended(resolution.FailReason)
                    ? true
                    : (bool?)null,
                    retryHint = SemanticRetryHint(resolution.FailReason, operation, deadlineMs,
                    maxDeadlineMs),
                    retry = truncated
                    ? null
                    : new
                    {
                        tool = "search_symbol",
                        arguments = new
                        {
                            query = candidateName,
                            match = "exact",
                            lang = "csharp",
                        },
                    },
                    documentationIdCoverage = DocumentationIdCoverageJson(resolution.Coverage,
                    skippedProjects, skippedProjectsTruncated),
                    timing = new
                    {
                        deadlineMs,
                        effectiveDeadlineMs = deadlineMs,
                        maxDeadlineMs,
                        elapsedMs = deadlineStopwatch.ElapsedMilliseconds,
                        documentationIdResolutionMs = deadlineStopwatch.ElapsedMilliseconds,
                        semanticColdStart = coldStartTiming.Timing,
                    },
                    meta = Meta.From(_manager.Health(), "indexed", "semantic"),
                }), resolution.FailReason?.StartsWith("semantic_error:",
                    StringComparison.Ordinal) == true ? "error" : "degraded",
                resolution.FailReason));
        }
        List<DocumentationIdResolution> matches = resolution.Matches;
        if (matches.Count == 0)
        {
            string reason = resolution.MissReason ?? "documentation_id_not_found";
            return (null, TerminalResponse(DocumentationIdNotFound(
                id, operation, candidateName, reason, resolution.Coverage,
                deadlineMs, deadlineStopwatch, coldStartTiming.Timing),
                "unresolved", reason));
        }
        if (matches.Count > 1)
        {
            bool coverageIncomplete = !resolution.Coverage.CompilerScanned;
            string reason = coverageIncomplete
                ? "documentation_id_coverage_incomplete"
                : "documentation_id_ambiguous";
            return (null, TerminalResponse(DocumentationIdCandidateEvidence(
                id, operation, matches, resolution.Coverage, coverageIncomplete,
                deadlineMs, deadlineStopwatch, coldStartTiming.Timing),
                coverageIncomplete ? "partial" : "unresolved", reason));
        }
        if (!resolution.Coverage.CompilerScanned)
        {
            const string reason = "documentation_id_coverage_incomplete";
            return (null, TerminalResponse(DocumentationIdCandidateEvidence(
                id, operation, matches, resolution.Coverage, coverageIncomplete: true,
                deadlineMs, deadlineStopwatch, coldStartTiming.Timing),
                "partial", reason));
        }
        DocumentationIdResolution resolved = matches[0];
        if (resolution.SnapshotIdentity is null)
        {
            return (null, TerminalResponse(DocumentationIdErrorWithCoverage(
                id, resolution.Coverage,
                (boundedId, truncated, skippedProjects, skippedProjectsTruncated) => new
                {
                    error = "semantic_unavailable",
                    operation,
                    documentationCommentId = boundedId,
                    documentationCommentIdTruncated = truncated ? true : (bool?)null,
                    documentationCommentIdBytes = truncated ? Json.Utf8Bytes(id) : (int?)null,
                    partialReason = "index_snapshot_unavailable",
                    retryRecommended = true,
                    retryHint = $"Retry {operation} once with the same arguments.",
                    documentationIdCoverage = DocumentationIdCoverageJson(resolution.Coverage,
                        skippedProjects, skippedProjectsTruncated),
                    timing = SemanticColdStartTimingJson(coldStartTiming, deadlineMs,
                        deadlineStopwatch, deadlineStopwatch.ElapsedMilliseconds),
                    meta = Meta.From(_manager.Health(), "indexed", "semantic"),
                }), "unresolved", "index_snapshot_unavailable"));
        }
        return (new DocumentationTarget(
            resolved.Name,
            resolved.NavigationPath,
            resolved.NavigationLine,
            resolved.NavigationColumn,
            resolved.CanonicalDocumentationCommentId,
            resolution.Coverage,
            resolution.SnapshotIdentity,
            deadlineStopwatch.ElapsedMilliseconds), null);
    }

    private string DocumentationIdCandidateEvidence(
        string id,
        string operation,
        List<DocumentationIdResolution> matches,
        DocumentationIdResolutionCoverage coverage,
        bool coverageIncomplete,
        int deadlineMs,
        System.Diagnostics.Stopwatch deadlineStopwatch,
        SemanticColdStartTiming? semanticColdStart)
    {
        HashSet<(string Path, int Line, int Column)> sharedPositions = matches
            .GroupBy(match => (match.NavigationPath, match.NavigationLine,
                match.NavigationColumn))
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToHashSet();
        bool sharedPosition = sharedPositions.Count > 0;

        object BuildResponse(
            string boundedId,
            bool idTruncated,
            List<DocumentationIdResolution> items,
            bool truncated,
            List<string> skippedProjects,
            bool skippedProjectsTruncated)
        {
            bool ambiguous = matches.Count > 1;
            return new
            {
                error = ambiguous
                    ? "symbol_ambiguous"
                    : "documentation_id_coverage_incomplete",
                operation,
                documentationCommentId = boundedId,
                documentationCommentIdTruncated = idTruncated ? true : (bool?)null,
                documentationCommentIdBytes = idTruncated ? Json.Utf8Bytes(id) : (int?)null,
                reason = coverageIncomplete
                    ? "documentation_id_coverage_incomplete"
                    : null,
                detail = ambiguous
                    ? coverageIncomplete
                        ? "At least two compiler identities match this documentation id, and the compiler sweep was incomplete, so more candidates may exist. Inspect project/assembly evidence and use a candidate's position recovery when it is available."
                        : "The declaration id exists in multiple workspace assemblies. Inspect project/assembly evidence and use a candidate's position recovery; Phoenix never chooses the first assembly."
                    : "Compiler coverage was incomplete, so this matching declaration is evidence only and Phoenix will not claim it is unique. Use its position recovery after inspecting skipped projects.",
                candidateCount = matches.Count,
                candidateCountIsLowerBound = coverageIncomplete ? true : (bool?)null,
                candidatesReturned = items.Count,
                candidates = items.Select(match =>
                {
                    var position = (match.NavigationPath, match.NavigationLine,
                        match.NavigationColumn);
                    return new
                    {
                        confidence = "exact",
                        project = match.ProjectName,
                        assembly = match.Declaration.Assembly,
                        position = new
                        {
                            path = match.NavigationPath,
                            line = match.NavigationLine,
                            column = match.NavigationColumn,
                        },
                        recovery = sharedPositions.Contains(position)
                            ? null
                            : new
                            {
                                tool = operation,
                                replayOriginalRequest = true,
                                remove = DocumentationIdSelectorArguments(operation),
                                arguments = DocumentationIdPositionArguments(operation, match),
                            },
                    };
                }),
                selectionRequired = true,
                truncated = truncated ? true : (bool?)null,
                partial = coverageIncomplete ? true : (bool?)null,
                partialReason = coverageIncomplete
                    ? "documentation_id_coverage_incomplete"
                    : null,
                noteId = sharedPosition ? NoteIds.DocumentationIdPositionShared : null,
                note = sharedPosition
                    ? "Some compiler identities share one source position across projects. Recovery is omitted only for those candidates because this tool has no project/assembly selector; inspect their project and assembly evidence explicitly."
                    : null,
                documentationIdCoverage = DocumentationIdCoverageJson(coverage,
                    skippedProjects, skippedProjectsTruncated),
                timing = semanticColdStart is null
                    ? null
                    : new
                    {
                        deadlineMs,
                        elapsedMs = deadlineStopwatch.ElapsedMilliseconds,
                        documentationIdResolutionMs = deadlineStopwatch.ElapsedMilliseconds,
                        semanticColdStart,
                    },
                meta = Meta.From(_manager.Health(),
                    coverageIncomplete ? "indexed" : "exact", "semantic"),
            };
        }

        string BuildBudgeted(string boundedId, bool idTruncated) =>
            Json.WithDiagnosticListBudget(matches,
                coverage.SkippedProjects.ToList(),
                (budgetedItems, truncated, skippedProjects, skippedProjectsTruncated) =>
                {
                    bool candidateFloorApplied = budgetedItems.Count == 0 && matches.Count > 0;
                    List<DocumentationIdResolution> items = candidateFloorApplied
                        ? matches.Take(1).ToList()
                        : budgetedItems;
                    return BuildResponse(boundedId, idTruncated, items,
                        truncated || candidateFloorApplied, skippedProjects,
                        skippedProjectsTruncated);
                });

        try
        {
            return Json.WithStringBudget(id, Json.HardBudgetBytes,
                (boundedId, idTruncated) =>
                    System.Text.Json.Nodes.JsonNode.Parse(
                        BuildBudgeted(boundedId, idTruncated))!);
        }
        catch (InvalidOperationException)
        {
            // The reflected caller id is optional recovery context; preserve one complete exact
            // candidate instead. If that indivisible position/assembly identity alone exceeds the
            // ordinary target, use the same measured exception as other compiler identities.
            string floor = Json.Serialize(BuildResponse("", id.Length > 0,
                matches.Take(1).ToList(), truncated: true, [],
                skippedProjectsTruncated: coverage.SkippedProjects.Count > 0));
            return Json.WithCompleteSemanticIdentity(floor);
        }
    }

    private static object DocumentationIdPositionArguments(
        string operation,
        DocumentationIdResolution match) => operation == "implementations"
        ? new
        {
            path = match.NavigationPath,
            line = match.NavigationLine,
            column = match.NavigationColumn,
        }
        : new
        {
            path = match.NavigationPath,
            line = match.NavigationLine,
            column = match.NavigationColumn,
            mode = "semantic",
        };

    private static string[] DocumentationIdSelectorArguments(string operation) =>
        operation switch
        {
            "definition" =>
            [
                "name", "container", "kinds", "path", "line", "column", "symbolId",
                "documentationCommentId", "projectPath", "targetFramework",
            ],
            "implementations" =>
            [
                "name", "path", "line", "column", "arity", "symbolId",
                "documentationCommentId",
            ],
            _ =>
            [
                "name", "path", "line", "column", "symbolId",
                "documentationCommentId", "projectPath", "targetFramework",
            ],
        };

    private string DocumentationIdNotFound(
        string id,
        string operation,
        string candidateName,
        string reason,
        DocumentationIdResolutionCoverage coverage,
        int deadlineMs,
        System.Diagnostics.Stopwatch deadlineStopwatch,
        SemanticColdStartTiming? semanticColdStart) =>
        DocumentationIdErrorWithCoverage(id, coverage,
            (boundedId, truncated, skippedProjects, skippedProjectsTruncated) => new
            {
                error = "symbol_not_found",
                operation,
                documentationCommentId = boundedId,
                documentationCommentIdTruncated = truncated ? true : (bool?)null,
                documentationCommentIdBytes = truncated ? Json.Utf8Bytes(id) : (int?)null,
                reason,
                detail = coverage.CompilerScanned
                ? "The compiler completed the requested project sweep and found no source declaration with this documentation id."
                : "The index could not identify a C# compile owner for this documentation id, so absence is not compiler-proven.",
                retry = truncated
                ? null
                : new
                {
                    tool = "search_symbol",
                    arguments = new
                    {
                        query = candidateName,
                        match = "exact",
                        lang = "csharp",
                    },
                },
                partial = coverage.CompilerScanned ? (bool?)null : true,
                partialReason = coverage.CompilerScanned ? null : reason,
                documentationIdCoverage = DocumentationIdCoverageJson(coverage,
                skippedProjects, skippedProjectsTruncated),
                timing = semanticColdStart is null
                ? null
                : new
                {
                    deadlineMs,
                    elapsedMs = deadlineStopwatch.ElapsedMilliseconds,
                    documentationIdResolutionMs = deadlineStopwatch.ElapsedMilliseconds,
                    semanticColdStart,
                },
                meta = Meta.From(_manager.Health(),
                coverage.CompilerScanned ? "exact" : "indexed",
                coverage.CompilerScanned ? "semantic" : "syntax"),
            });

    private static object DocumentationIdCoverageJson(
        DocumentationIdResolutionCoverage coverage,
        IReadOnlyCollection<string>? skippedProjects = null,
        bool skippedProjectsTruncated = false)
    {
        int skippedTotal = coverage.SkippedProjects.Count;
        int skippedReturned = skippedProjects?.Count ?? 0;
        return new
        {
            coverage.SeedFiles,
            coverage.SeedProjects,
            coverage.RequestedProjects,
            coverage.LoadedProjects,
            coverage.ScannedProjects,
            skippedProjectCount = skippedTotal > 0 ? skippedTotal : (int?)null,
            skippedProjects = skippedReturned > 0
                ? skippedProjects
                : null,
            skippedProjectsReturned = skippedTotal > 0 ? skippedReturned : (int?)null,
            skippedProjectsTruncated = skippedTotal > skippedReturned || skippedProjectsTruncated
                ? true
                : (bool?)null,
            compilerScanned = coverage.CompilerScanned,
            nameKeyedOwnerCollisionGroups = coverage.NameKeyedOwnerCollisionGroups > 0
                ? coverage.NameKeyedOwnerCollisionGroups
                : (int?)null,
            noteId = coverage.NameKeyedOwnerCollisionGroups > 0
                ? NoteIds.DocumentationIdNameKeyedOwnerCollision
                : null,
            note = coverage.NameKeyedOwnerCollisionGroups > 0
                ? "C# semantic compilation and the reference graph are assembly-name-keyed, and this request's owner set includes same-name physical projects beyond the recognized legacy/.Net companion pair. Results reflect the compiler model's one binding for that name; the physical index rows remain separate — read nameKeyedOwnerCollisionGroups and select a physical row by exact project-file path."
                : null,
        };
    }

    private static string DocumentationIdErrorWithCoverage(
        string documentationCommentId,
        DocumentationIdResolutionCoverage coverage,
        Func<string, bool, List<string>, bool, object> build) =>
        Json.WithStringBudget(documentationCommentId, Json.HardBudgetBytes,
            (boundedId, idTruncated) =>
            {
                string json = Json.WithListBudget(coverage.SkippedProjects.ToList(),
                    (skippedProjects, skippedProjectsTruncated) => build(
                        boundedId, idTruncated, skippedProjects,
                        skippedProjectsTruncated));
                return System.Text.Json.Nodes.JsonNode.Parse(json)!;
            });

    private static string DocumentationIdError(
        string documentationCommentId,
        Func<string, bool, object> build) => Json.WithStringBudget(
            documentationCommentId,
            Json.HardBudgetBytes,
            build);

    private static int RemainingDeadlineMilliseconds(
        int deadlineMs,
        System.Diagnostics.Stopwatch stopwatch) =>
        Math.Max(1, deadlineMs - (int)Math.Min(int.MaxValue, stopwatch.ElapsedMilliseconds));

    private static object? SemanticColdStartTimingJson(
        SemanticColdStartTimingBox timingBox,
        int deadlineMs,
        System.Diagnostics.Stopwatch stopwatch,
        long? documentationIdResolutionMs = null)
    {
        SemanticColdStartTiming? timing = timingBox.Timing;
        return timing is null
            ? null
            : new
            {
                deadlineMs,
                elapsedMs = stopwatch.ElapsedMilliseconds,
                documentationIdResolutionMs,
                semanticColdStart = timing,
            };
    }

    private string DocumentationIdIdentityMismatch(
        string callerDocumentationCommentId,
        string expectedCanonicalId,
        string? observedCanonicalId,
        string operation,
        DocumentationIdResolutionCoverage? coverage,
        int deadlineMs,
        System.Diagnostics.Stopwatch stopwatch,
        long? documentationIdResolutionMs,
        SemanticColdStartTiming? semanticColdStart) =>
        DocumentationIdError(callerDocumentationCommentId, (boundedId, truncated) => new
        {
            error = "semantic_identity_mismatch",
            operation,
            documentationCommentId = boundedId,
            documentationCommentIdTruncated = truncated ? true : (bool?)null,
            documentationCommentIdBytes = truncated
                ? Json.Utf8Bytes(callerDocumentationCommentId)
                : (int?)null,
            expectedCanonicalIdentityPresent = expectedCanonicalId.Length > 0,
            observedCanonicalIdentityPresent = observedCanonicalId is { Length: > 0 },
            detail = "The downstream compiler operation resolved a different symbol than documentationCommentId resolution. No indexed or name-based fallback was returned.",
            documentationIdCoverage = coverage is null
                ? null
                : DocumentationIdCoverageJson(coverage),
            timing = new
            {
                deadlineMs,
                elapsedMs = stopwatch.ElapsedMilliseconds,
                documentationIdResolutionMs,
                semanticColdStart,
            },
            meta = Meta.From(_manager.Health(), "indexed", "semantic"),
        });

    private sealed record ResolvedProjectSelector(
        ProjectRow Project,
        List<ProjectSelectorMatch> ShadowedMatches);

    private sealed record ProjectSelectorShadow(
        string Field,
        ProjectSelectorMatch Match);

    private (ResolvedProjectSelector? Project, string? Error) ResolveProjectSelector(
        IndexQueries queries,
        string selector,
        string field,
        string operation)
    {
        if (string.IsNullOrWhiteSpace(selector))
            return (null, Json.Serialize(new
            {
                error = "bad_request",
                field,
                detail = $"Provide '{field}'.",
            }));
        ProjectSelectorResolution resolution = queries.ProjectsBySelector(selector);
        if (TestOnlyProjectSelectorResolutionTransform is not null)
            resolution = TestOnlyProjectSelectorResolutionTransform(resolution);
        List<ProjectSelectorMatch> matches = resolution.Matches;
        if (matches.Count == 1)
            return (new ResolvedProjectSelector(matches[0].Project,
                resolution.ShadowedMatches), null);
        if (matches.Count > 1)
        {
            bool sameLogicalName = matches.Select(match => match.Project.Name)
                .Distinct(StringComparer.OrdinalIgnoreCase).Count() == 1;
            return (null, ProjectSelectorResponse(selector, matches,
                resolution.ShadowedMatches,
                (boundedSelector, selectorTruncated, items, truncated,
                    shadowedMatches, shadowedMatchesTruncated) => new
                    {
                        error = "project_ambiguous",
                        field,
                        selector = boundedSelector,
                        selectorTruncated = selectorTruncated ? true : (bool?)null,
                        selectorBytes = selectorTruncated ? Json.Utf8Bytes(selector) : (int?)null,
                        detail = sameLogicalName
                        ? "The selector matches multiple physical project rows with one assembly name. Use an exact project-file path to select the physical row; semantic and graph answers are assembly-name-keyed and can therefore be identical for the listed paths."
                        : "The selector matches multiple physical projects. Use an exact project-file path; Phoenix never picks the first match.",
                        sameLogicalName = sameLogicalName ? true : (bool?)null,
                        totalMatches = matches.Count,
                        matches = items.Select(match => new
                        {
                            match.Project.Name,
                            match.Project.Path,
                            language = match.Project.Language,
                            matchedBy = match.MatchedBy,
                        }),
                        matchesReturned = items.Count,
                        truncated,
                        projectSelectorResolution = ProjectSelectorResolutionJson(
                        resolution.ShadowedMatches.Count, shadowedMatches,
                        shadowedMatchesTruncated),
                        meta = Meta.From(_manager.Health(), "indexed", "text"),
                    }));
        }
        ProjectSuggestionResult suggestions = queries.SuggestProjects(
            selector, DefaultResultLimit);
        return (null, ProjectSelectorResponse(selector, suggestions.Matches.ToList(),
            resolution.ShadowedMatches,
            (boundedSelector, selectorTruncated, items, truncated,
                shadowedMatches, shadowedMatchesTruncated) => new
                {
                    error = "project_not_found",
                    field,
                    selector = boundedSelector,
                    selectorTruncated = selectorTruncated ? true : (bool?)null,
                    selectorBytes = selectorTruncated ? Json.Utf8Bytes(selector) : (int?)null,
                    reason = "project_not_found",
                    suggestions = items.Select(match => new
                    {
                        match.Project.Name,
                        match.Project.Path,
                        language = match.Project.Language,
                        rationale = match.MatchedBy,
                        recovery = new
                        {
                            tool = operation,
                            replayOriginalRequest = true,
                            remove = new[] { field },
                            arguments = new Dictionary<string, object?>
                            {
                                [field] = match.Project.Path,
                            },
                        },
                    }),
                    suggestionCoverage = new
                    {
                        suggestions.Probed,
                        suggestions.ProbeLimit,
                        suggestions.ProbeTruncated,
                        returned = items.Count,
                        truncated = truncated || suggestions.Matches.Count > items.Count
                        ? true
                        : (bool?)null,
                    },
                    projectSelectorResolution = ProjectSelectorResolutionJson(
                    resolution.ShadowedMatches.Count, shadowedMatches,
                    shadowedMatchesTruncated),
                    meta = Meta.From(_manager.Health(), "indexed", "text"),
                }));
    }

    private string ProjectSelectorResponse<T>(
        string selector,
        List<T> items,
        List<ProjectSelectorMatch> shadowedMatches,
        Func<string, bool, List<T>, bool, List<ProjectSelectorMatch>, bool, object> build) =>
        Json.WithStringBudget(selector, Json.HardBudgetBytes,
            (boundedSelector, selectorTruncated) =>
                System.Text.Json.Nodes.JsonNode.Parse(Json.WithDiagnosticListBudget(
                    items, shadowedMatches,
                    (boundedItems, itemsTruncated, boundedShadowedMatches,
                        shadowedMatchesTruncated) => build(
                        boundedSelector, selectorTruncated,
                        boundedItems, itemsTruncated,
                        boundedShadowedMatches, shadowedMatchesTruncated),
                    TestOnlyProjectSelectorResponseMaxBytes))!,
            TestOnlyProjectSelectorResponseMaxBytes);

    private static object? ProjectSelectorResolutionJson(
        int shadowedMatchCount,
        IReadOnlyCollection<ProjectSelectorMatch> shadowedMatches,
        bool shadowedMatchesTruncated) => shadowedMatchCount == 0
        ? null
        : new
        {
            selectedByPrecedence = true,
            shadowedMatchCount,
            shadowedMatches = shadowedMatches.Select(match => new
            {
                match.Project.Name,
                match.Project.Path,
                language = match.Project.Language,
                matchedBy = match.MatchedBy,
            }),
            shadowedMatchesReturned = shadowedMatches.Count,
            shadowedMatchesTruncated = shadowedMatchCount > shadowedMatches.Count ||
                                       shadowedMatchesTruncated
                ? true
                : (bool?)null,
            detail = "Lower-precedence selector classes also matched; the selected exact path or filename remains authoritative.",
        };

    internal static bool TryParsePathList(
        string? value,
        int maximumPaths,
        out List<string> paths,
        out string? detail)
    {
        paths = new List<string>();
        detail = null;
        if (string.IsNullOrWhiteSpace(value))
        {
            detail = "Provide 'paths'.";
            return false;
        }
        if (System.Text.Encoding.UTF8.GetByteCount(value) > PathListInputByteLimit)
        {
            detail = $"paths accepts at most {PathListInputByteLimit} UTF-8 bytes.";
            return false;
        }

        string trimmed = value.Trim();
        if (trimmed[0] == '[')
        {
            try
            {
                using JsonDocument document = JsonDocument.Parse(trimmed);
                if (document.RootElement.ValueKind != JsonValueKind.Array)
                {
                    detail = "paths must be comma-separated text or a JSON array of strings.";
                    return false;
                }

                foreach (JsonElement item in document.RootElement.EnumerateArray())
                {
                    if (item.ValueKind != JsonValueKind.String)
                    {
                        detail = "Every JSON-array paths item must be a non-empty string.";
                        return false;
                    }
                    if (!TryAddExplicitPath(item.GetString()!, maximumPaths, paths, out detail))
                        return false;
                }
            }
            catch (JsonException)
            {
                detail = "paths starts like a JSON array but is not a valid JSON array of strings.";
                return false;
            }
        }
        else if (trimmed[0] is '"' or '{')
        {
            detail = "paths must be comma-separated text or a JSON array of strings.";
            return false;
        }
        else
        {
            int start = 0;
            while (start <= value.Length)
            {
                int comma = value.IndexOf(',', start);
                ReadOnlySpan<char> item = comma < 0
                    ? value.AsSpan(start)
                    : value.AsSpan(start, comma - start);
                item = item.Trim();
                if (item.IsEmpty)
                {
                    detail = "Every comma-separated paths item must be non-empty.";
                    return false;
                }
                if (!TryAddExplicitPath(item.ToString(), maximumPaths, paths, out detail))
                    return false;
                if (comma < 0) break;
                start = comma + 1;
            }
        }

        if (paths.Count == 0)
        {
            detail = "Provide 'paths'.";
            return false;
        }

        return true;

        static bool TryAddExplicitPath(
            string path,
            int maximumPaths,
            List<string> parsed,
            out string? failure)
        {
            failure = null;
            if (string.IsNullOrWhiteSpace(path))
            {
                failure = "Every paths item must be a non-empty string.";
                return false;
            }
            if (parsed.Count >= maximumPaths)
            {
                failure = $"paths accepts at most {maximumPaths} entries.";
                return false;
            }
            if (!IsExactWorkspaceRelativePath(path, OperatingSystem.IsWindows()))
            {
                failure = $"paths item '{SafePathForError(path)}' must be an exact workspace-relative path without traversal or control characters.";
                return false;
            }
            parsed.Add(path);
            return true;
        }

        static string SafePathForError(string path)
        {
            const int limit = 96;
            string safe = new(path.Take(limit)
                .Select(character => char.IsControl(character) ? '\uFFFD' : character)
                .ToArray());
            return path.Length > limit ? safe + "…" : safe;
        }
    }

    internal static bool IsExactWorkspaceRelativePath(string path, bool windowsPathRules)
    {
        if (string.IsNullOrWhiteSpace(path) || path[0] == '/' ||
            path.StartsWith("\\\\", StringComparison.Ordinal) ||
            (path.Length >= 2 && char.IsAsciiLetter(path[0]) && path[1] == ':') ||
            (windowsPathRules && path.Contains(':', StringComparison.Ordinal)))
        {
            return false;
        }
        if (path.Any(char.IsControl)) return false;

        int segmentStart = 0;
        for (int index = 0; index <= path.Length; index++)
        {
            bool boundary = index == path.Length || path[index] == '/' ||
                (windowsPathRules && path[index] == '\\');
            if (!boundary) continue;
            ReadOnlySpan<char> segment = path.AsSpan(segmentStart, index - segmentStart);
            if (segment.IsEmpty || segment.SequenceEqual(".") || segment.SequenceEqual(".."))
                return false;
            segmentStart = index + 1;
        }
        return true;
    }

    internal static object? PathSuggestionsJson(
        int total,
        IReadOnlyList<string> paths,
        bool budgetTruncated)
    {
        if (total <= 0) return null;
        return new
        {
            paths,
            total,
            truncated = budgetTruncated || paths.Count < total,
        };
    }

    private static string NormalizePath(string path) => CodeNav.Core.WorkspacePaths.Normalize(path);
}
