namespace CodeNav.Core.Indexing;

/// <summary>
/// Owns: cheap generated-code heuristics for files (name patterns + auto-generated banners).
/// Does not own: test classification (project-level, resolved at query time) or exclusions
/// (WorkspaceScanner).
/// </summary>
public static class FileClassifier
{
    private static readonly string[] GeneratedNameSuffixes =
    {
        ".g.cs", ".g.i.cs", ".designer.cs", ".generated.cs", ".AssemblyAttributes.cs",
    };

    public static bool LooksGenerated(string relPath, string content)
    {
        string fileName = relPath;
        int slash = relPath.LastIndexOf('/');
        if (slash >= 0) fileName = relPath[(slash + 1)..];

        foreach (var suffix in GeneratedNameSuffixes)
        {
            if (fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)) return true;
        }
        if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase)) return true;

        // <auto-generated> banner in the first ~400 chars.
        int probe = Math.Min(content.Length, 400);
        var head = content.AsSpan(0, probe);
        return head.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
               head.Contains("<autogenerated", StringComparison.OrdinalIgnoreCase);
    }
}
