using System.Text.Json;
using CodeNav.Core.Indexing;
using CodeNav.Core.Semantic;
using CodeNav.Mcp;

namespace CodeNav.Tests;

public class Batch71SymbolFreeOutlineTests
{
    [Fact]
    public void OutlineAndBatchOutlinePreserveIndexedSymbolFreeCSharpFiles()
    {
        string root = Directory.CreateTempSubdirectory("codenav-b4on").FullName;
        try
        {
            string projectDirectory = Path.Combine(root, "P");
            Directory.CreateDirectory(projectDirectory);
            File.WriteAllText(Path.Combine(projectDirectory, "P.csproj"),
                """
                <Project Sdk="Microsoft.NET.Sdk">
                  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
                </Project>
                """);
            File.WriteAllText(Path.Combine(projectDirectory, "CommentsOnly.cs"),
                "// This owned C# file intentionally declares no symbols.\n");
            File.WriteAllText(Path.Combine(projectDirectory, "Empty.g.cs"),
                "// <auto-generated />\nglobal using System;\n");

            string databasePath = IndexBuilder.DefaultDbPath(root);
            IndexBuilder.Build(root, databasePath);
            using var manager = new IndexManager(root, databasePath);
            manager.Start();
            Assert.True(WaitUntil(() => manager.IsQueryable, TimeSpan.FromSeconds(30)),
                "index did not become queryable");
            using var semantic = new SemanticService(manager);
            var tools = new NavigationTools(manager, semantic);

            JsonElement commentsOnly = Parse(tools.Outline("P/CommentsOnly.cs"));
            JsonElement generated = Parse(tools.Outline("P/Empty.g.cs"));
            AssertEmptyOutline(commentsOnly, "P/CommentsOnly.cs", isGenerated: false);
            AssertEmptyOutline(generated, "P/Empty.g.cs", isGenerated: true);

            JsonElement batch = Parse(tools.BatchOutline(
                JsonSerializer.Serialize(new[] { "P/CommentsOnly.cs", "P/Empty.g.cs" })));
            JsonElement[] outlines = batch.GetProperty("outlines").EnumerateArray().ToArray();
            Assert.Equal(2, outlines.Length);
            Assert.False(batch.GetProperty("truncated").GetBoolean());
            AssertEmptyOutline(outlines[0], "P/CommentsOnly.cs", isGenerated: false);
            AssertEmptyOutline(outlines[1], "P/Empty.g.cs", isGenerated: true);
        }
        finally
        {
            TestWorkspaceCleanup.DeleteWorkspace(root);
        }
    }

    private static void AssertEmptyOutline(JsonElement outline, string path, bool isGenerated)
    {
        Assert.False(outline.TryGetProperty("error", out _));
        Assert.Equal(path, outline.GetProperty("path").GetString());
        Assert.Equal(isGenerated, outline.GetProperty("isGenerated").GetBoolean());
        Assert.Empty(outline.GetProperty("symbols").EnumerateArray());
        Assert.False(outline.GetProperty("truncated").GetBoolean());
        Assert.Equal("indexed", outline.GetProperty("meta").GetProperty("confidence").GetString());
        Assert.Equal("syntax", outline.GetProperty("meta").GetProperty("navigationLayer").GetString());
    }

    private static JsonElement Parse(string json) => JsonDocument.Parse(json).RootElement;

    private static bool WaitUntil(Func<bool> condition, TimeSpan timeout)
    {
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();
        while (stopwatch.Elapsed < timeout)
        {
            if (condition()) return true;
            Thread.Sleep(50);
        }
        return condition();
    }
}
