using System.Text.Json;
using CodeNav.Core.Indexing;
using CodeNav.Core.Semantic;
using CodeNav.Mcp;
using CodeNav.WorkspaceGen;

namespace CodeNav.Tests;

/// <summary>
/// search_text dead-end hints (oec + xyy + ymp cardinality). Field evidence: an agent scoped pathGlob
/// to the wrong dir, got a CORRECT 0, and — with no signal about where matches actually live — fell
/// back to manually reading ~10 files. The index knows where matches are; a zero-hit response must
/// redirect ("elsewhere"), say "absent everywhere" honestly, or steer (partial-leads / common-term).
/// And on a clean success the note is OMITTED (the old verbatim explainer was per-call token waste).
/// </summary>
public class Batch17SearchTextHintsTests : IDisposable
{
    private readonly string _root;
    private readonly IndexManager _manager;
    private readonly NavigationTools _tools;
    private readonly SemanticService _semantic;

    public Batch17SearchTextHintsTests()
    {
        _root = Directory.CreateTempSubdirectory("codenav-hints").FullName;
        WorkspaceGenerator.Generate(_root, targetProjects: 2, seed: 3);
        // The field scenario: the real content lives in a subdir the agent won't guess.
        Directory.CreateDirectory(Path.Combine(_root, "Widen"));
        File.WriteAllText(Path.Combine(_root, "Widen", "HintTarget.cs"),
            "namespace W { class H { int ZzWidenMarker; } }");
        // A token that exists ONLY in a generated file (default includeGenerated=false hides it).
        File.WriteAllText(Path.Combine(_root, "GenOnly.g.cs"),
            "// <auto-generated/>\nnamespace G { class GG { int ZzGenOnlyMarker; } }");
        // A very common term (>= 1000 precise lines) for the cardinality warning.
        File.WriteAllText(Path.Combine(_root, "Common.cs"),
            "namespace C { class CC {\n" + string.Concat(Enumerable.Repeat("// CommonZzTok pad\n", 1500)) + "} }");
        // Two tokens that co-occur in one file but never on one line (partial-leads nudge).
        File.WriteAllText(Path.Combine(_root, "Partial.cs"),
            "namespace P { class PP {\n// ZzAlphaTok\n// ZzBetaTok\n} }");

        string dbPath = IndexBuilder.DefaultDbPath(_root);
        IndexBuilder.Build(_root, dbPath);
        _manager = new IndexManager(_root, dbPath);
        _manager.Start();
        for (int i = 0; i < 100 && !_manager.IsQueryable; i++) Thread.Sleep(50);
        _semantic = new SemanticService(_manager);
        _tools = new NavigationTools(_manager, _semantic);
    }

    public void Dispose()
    {
        _semantic.Dispose();
        _manager.Dispose();
        TestWorkspaceCleanup.ClearIndexPools(_root);
        try { Directory.Delete(_root, recursive: true); } catch { /* leave temp on Windows lock */ }
    }

    private static JsonElement Parse(string json) => JsonDocument.Parse(json).RootElement;

    // oec: a scoped zero-hit redirects to where matches actually exist instead of a bare dead end.
    [Fact]
    public void ScopedZeroHitRedirectsToWhereMatchesExist()
    {
        var r = Parse(_tools.SearchText("ZzWidenMarker", pathGlob: "NoSuchDir/**"));
        Assert.Equal(0, r.GetProperty("preciseCount").GetInt32());
        var elsewhere = r.GetProperty("elsewhere");
        Assert.True(elsewhere.GetProperty("preciseCount").GetInt32() >= 1);
        Assert.Contains("Widen/HintTarget.cs",
            elsewhere.GetProperty("samplePaths").EnumerateArray().Select(p => p.GetString()));
        Assert.Contains("widen", r.GetProperty("note").GetString(), StringComparison.OrdinalIgnoreCase);
    }

    // oec: unscoped zero-hit with no matches anywhere says so honestly (no wild-goose chase). The
    // claim is index-wide only because an FTS AND that matched zero files proves it — a review killed
    // the earlier "anywhere in the index" wording for multi-token queries above the probe cap.
    [Fact]
    public void AbsentTermSaysAbsentEverywhere()
    {
        var r = Parse(_tools.SearchText("ZzAbsentTokNine"));
        Assert.Equal(0, r.GetProperty("preciseCount").GetInt32());
        Assert.False(r.TryGetProperty("elsewhere", out _));
        Assert.Contains("No file contains all query tokens together", r.GetProperty("note").GetString());
    }

    // Review finding: tokens that co-occur (probe partials) must NOT be declared absent — the honest
    // message is "they co-occur across lines", with the co-occurring files as the redirect.
    [Fact]
    public void CoOccurringTokensRedirectInsteadOfAbsentClaim()
    {
        var r = Parse(_tools.SearchText("ZzAlphaTok ZzBetaTok", pathGlob: "NoSuchDir/**"));
        Assert.Equal(0, r.GetProperty("preciseCount").GetInt32());
        Assert.Contains("co-occur", r.GetProperty("note").GetString());
        Assert.Contains("Partial.cs",
            r.GetProperty("elsewhere").GetProperty("samplePaths").EnumerateArray().Select(p => p.GetString()));
    }

    // A query with no indexable tokens (pure punctuation) says so instead of claiming absence.
    [Fact]
    public void TokenFreeQuerySaysNoIndexableTokens()
    {
        var r = Parse(_tools.SearchText("=> ??"));
        Assert.Contains("no indexable tokens", r.GetProperty("note").GetString());
    }

    // oec: a term that lives only in generated files points at includeGenerated instead of "absent".
    [Fact]
    public void GeneratedOnlyTermPointsAtIncludeGenerated()
    {
        var r = Parse(_tools.SearchText("ZzGenOnlyMarker"));
        Assert.Equal(0, r.GetProperty("preciseCount").GetInt32());
        Assert.Contains("includeGenerated", r.GetProperty("note").GetString());
    }

    // partials steering: 0 precise but cross-line leads exist -> nudge to partials:'always'.
    [Fact]
    public void PartialLeadsNudgeWhenPreciseIsZero()
    {
        var r = Parse(_tools.SearchText("ZzAlphaTok ZzBetaTok"));
        Assert.Equal(0, r.GetProperty("preciseCount").GetInt32());
        Assert.True(r.GetProperty("partialCount").GetInt32() >= 2);
        Assert.Contains("partials:'always'", r.GetProperty("note").GetString());
        Assert.True(r.GetProperty("filesMatchedAcrossLines").GetArrayLength() >= 1);
    }

    // ymp cardinality: a very common term warns instead of silently serving a truncated sample.
    [Fact]
    public void CommonTermGetsCardinalityWarning()
    {
        var r = Parse(_tools.SearchText("CommonZzTok", limit: 5));
        Assert.True(r.GetProperty("preciseCount").GetInt32() >= 1000);
        Assert.Contains("Common term", r.GetProperty("note").GetString());
    }

    // xyy: a clean success carries NO note and NO elsewhere — zero steering overhead per call.
    [Fact]
    public void CleanSuccessOmitsNoteAndElsewhere()
    {
        var r = Parse(_tools.SearchText("ZzWidenMarker"));
        Assert.Equal(1, r.GetProperty("preciseCount").GetInt32());
        Assert.False(r.TryGetProperty("note", out _));
        Assert.False(r.TryGetProperty("elsewhere", out _));
    }
}
