using System.Text.Json;
using CodeNav.Core.Indexing;
using CodeNav.Core.Semantic;
using CodeNav.Mcp;
using CodeNav.WorkspaceGen;
using Microsoft.Data.Sqlite;

namespace CodeNav.Tests;

/// <summary>
/// references includeGenerated (bug wi3): generated-file usages must be excluded from BOTH the counts
/// and the samples when includeGenerated=false (the default). Previously the semantic path ignored the
/// flag entirely and the indexed path filtered only samples, leaving counts inflated by generated hits.
/// This exercises the indexed path (ReferenceCandidates SQL filter) and the GeneratedPaths helper the
/// semantic path uses to skip generated locations.
/// </summary>
public class Batch15ReferencesGeneratedTests
{
    private static JsonElement Parse(string json) => JsonDocument.Parse(json).RootElement;

    [Fact]
    public void ReferencesIndexedExcludesGeneratedFromCountsAndSamples()
    {
        string root = Directory.CreateTempSubdirectory("codenav-wi3").FullName;
        try
        {
            WorkspaceGenerator.Generate(root, targetProjects: 2, seed: 8);
            // The same unique token used in one normal file and one generated file (.g.cs + banner).
            File.WriteAllText(Path.Combine(root, "WiRef.cs"),
                "namespace W { class C { int WiThreeMarker; } }");
            File.WriteAllText(Path.Combine(root, "WiGen.g.cs"),
                "// <auto-generated/>\nnamespace W { class G { int WiThreeMarker; } }");

            string dbPath = IndexBuilder.DefaultDbPath(root);
            IndexBuilder.Build(root, dbPath);

            var manager = new IndexManager(root, dbPath);
            try
            {
                manager.Start();
                for (int i = 0; i < 100 && !manager.IsQueryable; i++) Thread.Sleep(50);
                Assert.True(manager.IsQueryable);

                using (var q = manager.OpenQueries())
                    Assert.Contains("WiGen.g.cs", q.GeneratedPaths()); // the helper the semantic path uses

                var tools = new NavigationTools(manager, new SemanticService(manager));
                int incTrue = Parse(tools.References(name: "WiThreeMarker", mode: "indexed", includeGenerated: true))
                    .GetProperty("totalCandidates").GetInt32();
                var falseResp = Parse(tools.References(name: "WiThreeMarker", mode: "indexed", includeGenerated: false));
                int incFalse = falseResp.GetProperty("totalCandidates").GetInt32();

                Assert.True(incFalse < incTrue, $"generated refs not excluded from count: false={incFalse} true={incTrue}");
                var falseSamplePaths = falseResp.GetProperty("groups").EnumerateArray()
                    .SelectMany(g => g.GetProperty("samples").EnumerateArray())
                    .Select(s => s.GetProperty("path").GetString());
                Assert.DoesNotContain("WiGen.g.cs", falseSamplePaths); // and not in samples either
            }
            finally { manager.Dispose(); }
        }
        finally
        {
            SqliteConnection.ClearAllPools();
            try { Directory.Delete(root, recursive: true); } catch { /* leave temp on Windows lock */ }
        }
    }
}
